spring.application.name=demo
logging.level.org.springframework.batch=DEBUG
spring.batch.job.debug=true
spring.batch.job.enabled=false
spring.batch.job.name=jobMaking
spring.batch.initialize-schema=always

## sftp configuration
sftp.host=localhost
sftp.port=2223
sftp.user=ssh-test
#sftp.password=demo
sftp.remote-directory-input=/in
sftp.remote-directory-output=/out
sftp.file-extension = .gpg
# -- Uncomment this line if you want to use private key authentication
sftp.private-key=C:/Users/BDGSA/IdeaProjects/key_gpg/ssh_host_ed25519_key
## sftp.private-key-passphrase=your_passphrase

## pgp properties
pgp.passphrase=anibal.rodriguez.bdg
pgp.private-key=C:/Users/BDGSA/IdeaProjects/key_gpg/BDGSA_0x32093250EE689AF7_SECRET.asc
pgp.public-key=C:/Users/BDGSA/IdeaProjects/key_gpg/public_key.asc
pgp.enabled=true