spring.application.name=demo
logging.level.org.springframework.batch=DEBUG
spring.batch.job.enabled=false
## spring.batch.job.name=job1

## sftp configuration
sftp.host=localhost
sftp.port=2222
sftp.username=test
sftp.password=test
# -- Uncomment this line if you want to use private key authentication
## sftp.private-key=/opt/keys/id_rsa
## sftp.private-key-passphrase=your_passphrase

## pgp properties
pgp.passphrase = anibal.rodriguez.bdg
pgp.private-key = BDGSA_0x32093250EE689AF7_SECRET.asc
