spring.application.name=demo
logging.level.org.springframework.batch=DEBUG
spring.batch.job.enabled=false
## spring.batch.job.name=job1

## sftp configuration
sftp.host=localhost
sftp.port=2222
sftp.username=test
sftp.password=test
sftp.remote-input-file=upload/data.csv
sftp.remote-output-file=upload/output.csv
## sftp.private-key=/opt/keys/id_rsa -- Uncomment this line if you want to use private key authentication